Repository NHSDigital/Galleri-Frontend, pull requests merged in 2023-09, with the labels that each got.

#21 Gal 266/invitation planning param
  package-lock.json
  src/app/components/NavMenu.jsx
  src/app/models/invitation_planning/NationalForecastUptake.js
  src/app/models/invitation_planning/QuintileTarget.js
  src/app/page.jsx
  src/app/services/invitation_planning/InvitationPlanningService.js
  src/app/services/invitation_planning/mockInvitationPlanningParam.json
  src/app/views/invitation_planning/InvitationPlannin.test.js
  src/app/views/invitation_planning/InvitationPlanning.js
  src/app/views/invitation_planning/InvitationPlanningPage.jsx
  src/app/views/invitation_planning/NationalForecastUptakeTable.jsx
  src/app/views/invitation_planning/QuintileTargetTable.jsx
  src/app/views/invitation_planning/helper.js
Labels: enhancement

#22 Gal 266/hotfix
  src/app/views/invitation_planning/InvitationPlanning.js
Labels: bug

#23 fix the pipeline break
  .github/workflows/dependabot.yml
Labels: bug

#26 added minor changes to clinic summary screen
  .github/workflows/deploy-to-s3.yaml
  src/app/views/clinic_summary/ClinicSummary.test.js
  src/app/views/clinic_summary/ClinicSummaryPage.jsx
  src/app/views/clinic_summary/ClinicSummaryTable.jsx
Labels: frontend

#25 Gal 296/invitations screen clinic information
  .github/workflows/deploy-to-s3.yaml
  package-lock.json
  package.json
  src/app/components/NavMenu.jsx
  src/app/models/clinic_information/ClinicDetail.js
  src/app/page.jsx
  src/app/services/clinic_information/mockClinicInformation.json
  src/app/views/clinic_information/ClinicDetailsTable.jsx
  src/app/views/clinic_information/ClinicInformation.js
  src/app/views/clinic_information/ClinicInformation.test.js
  src/app/views/clinic_information/ClinicInformationPage.jsx
  src/app/views/clinic_information/RecentInvitationHistory.jsx
  src/app/views/clinic_information/WeeklyCapacityTable.jsx
  src/app/views/clinic_information/helper.js
Labels: frontend

#29 Gal 351/clinic summary backend
  package-lock.json
  src/app/page.jsx
  src/app/views/clinic_summary/ClinicSummary.js
  src/app/views/clinic_summary/ClinicSummary.test.js
  src/app/views/clinic_summary/ClinicSummaryPage.jsx
  src/app/views/clinic_summary/ClinicSummaryTable.jsx
  src/app/views/clinic_summary/helper.js
Labels: frontend
