Repository NHSDigital/Galleri-Frontend, pull requests merged in 2023-11, with the labels that each got.

#39 gal-557# Bug Fix to have View previous invitations link display and hide
  src/app/views/clinic_information/ClinicInformation.js
  src/app/views/clinic_information/ClinicInformationPage.jsx
  src/app/views/clinic_information/RecentInvitationHistory.jsx
  src/app/views/clinic_summary/ClinicSummary.js
  src/app/views/invitation_planning/InvitationPlanning.js
Labels: bug, frontend

#37 Gal 471/sort preinvite data
  src/app/page.jsx
  src/app/views/clinic_summary/ClinicSummaryTable.jsx
Labels: bug, frontend

#40 Gal 488/invitation summary page
  src/app/page.jsx
  src/app/styles/css/sass.css
  src/app/views/clinic_information/ClinicInformationPage.jsx
  src/app/views/invitation_summary/Actions.jsx
  src/app/views/invitation_summary/CheckDetailsBanner.jsx
  src/app/views/invitation_summary/ClinicInfo.jsx
  src/app/views/invitation_summary/ConfirmationBanner.jsx
  src/app/views/invitation_summary/ErrorBanner.jsx
  src/app/views/invitation_summary/InvitationSummary.js
  src/app/views/invitation_summary/InvitationSummary.test.js
  src/app/views/invitation_summary/InvitationSummaryPage.jsx
  src/app/views/invitation_summary/SummaryListFirst.jsx
  src/app/views/invitation_summary/SummaryListSecond.jsx
Labels: enhancement, frontend

#45 Gal 472/table no data defect
  package-lock.json
  src/app/models/Clinic.js
  src/app/page.jsx
  src/app/services/ClinicSummaryService.js
  src/app/services/mockClinicData.json
  src/app/services/mockIcbList.json
  src/app/views/clinic_information/ClinicInformation.js
  src/app/views/clinic_information/ClinicInformationPage.jsx
  src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitationCriteriaTable.jsx
  src/app/views/clinic_summary/ClinicSummary.js
  src/app/views/clinic_summary/ClinicSummary.test.js
  src/app/views/clinic_summary/ClinicSummaryPage.jsx
  src/app/views/invitation_planning/InvitationPlanning.js
Labels: bug, frontend

#38 Gal 403/clinic info lsoa table
  src/app/views/clinic_information/ClinicInformation.js
  src/app/views/clinic_information/ClinicInformation.test.js
  src/app/views/clinic_information/ClinicInformationPage.jsx
  src/app/views/clinic_information/LsoaTable.jsx
  src/app/views/clinic_summary/ClinicSummary.js
  src/app/views/invitation_planning/InvitationPlanning.js
Labels: enhancement, frontend

#46 Gal 438/routing
  src/app/context/AppStateContext.js
  src/app/page.jsx
  src/app/styles/css/sass.css
  src/app/views/clinic_information/ClinicInformation.js
  src/app/views/clinic_information/ClinicInformationPage.jsx
  src/app/views/clinic_summary/ClinicSummary.js
  src/app/views/clinic_summary/ClinicSummaryPage.jsx
  src/app/views/clinic_summary/ClinicSummaryTable.jsx
  src/app/views/invitation_planning/InvitationPlanning.js
  src/app/views/invitation_summary/Actions.jsx
  src/app/views/invitation_summary/ClinicInfo.jsx
  src/app/views/invitation_summary/InvitationSummary.js
  src/app/views/invitation_summary/InvitationSummaryPage.jsx
  src/app/views/invitation_summary/SummaryListFirst.jsx
Labels: enhancement, frontend

#55 Gal 606/branch 2
  src/app/components/pagination.js
  src/app/views/clinic_information/ClinicInformation.js
  src/app/views/clinic_information/ClinicInformationPage.jsx
  src/app/views/clinic_information/LsoaTable.jsx
  src/app/views/clinic_information/config/milesOptions.json
  src/app/views/clinic_summary/ClinicSummary.js
  src/app/views/invitation_planning/InvitationPlanning.js
Labels: frontend

#57 Removed hyperlink when availibity is 0 for a clinic.
  src/app/views/clinic_summary/ClinicSummaryTable.jsx
Labels: enhancement, frontend

#56 Gal-414 & Gal-315 - Calculate number to invite
  src/app/components/pagination.js
  src/app/context/AppStateContext.js
  src/app/views/clinic_information/ClinicInformation.js
  src/app/views/clinic_information/ClinicInformation.test.js
  src/app/views/clinic_information/ClinicInformationPage.jsx
  src/app/views/clinic_information/LsoaTable.jsx
  src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitationCriteriaTable.jsx
  src/app/views/clinic_summary/ClinicSummary.js
  src/app/views/invitation_summary/ErrorBanner.jsx
  src/app/views/invitation_summary/InvitationSummary.js
  src/app/views/invitation_summary/InvitationSummaryPage.jsx
  src/app/views/invitation_summary/SummaryListFirst.jsx
  src/app/views/invitation_summary/SummaryListSecond.jsx
Labels: enhancement, frontend
