Repository NHSDigital/Galleri-Frontend, pull requests merged in 2023-12, with the labels that each got.

#69 feature/GAL-465# reset state
  src/app/views/clinic_summary/ClinicSummary.js
  src/app/views/invitation_summary/InvitationSummary.js
Labels: frontend

#74 Gal 749/remove all prev invitation link
  .gitignore
  src/app/styles/css/sass.css
  src/app/views/clinic_information/RecentInvitationHistory.jsx
Labels: bug, frontend

#72 Feature/gal 602 error
  src/app/styles/css/sass.css
  src/app/views/clinic_information/ClinicInformation.js
  src/app/views/clinic_information/ClinicInformationPage.jsx
  src/app/views/clinic_information/ErrorBannerDetail.jsx
  src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitationCriteria.jsx
Labels: frontend

#71 Feature/GAL-600
  src/app/styles/css/sass.css
  src/app/views/clinic_information/ClinicInformation.js
  src/app/views/clinic_information/ClinicInformationPage.jsx
  src/app/views/clinic_information/ErrorBannerDetail.jsx
  src/app/views/clinic_information/LsoaTable.jsx
  src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitationCriteria.jsx
Labels: frontend

#81 Gal 774/accessibility clinic invitations
  src/app/styles/css/sass.css
  src/app/views/clinic_information/ClinicDetailsTable.jsx
  src/app/views/clinic_information/ClinicInformation.js
  src/app/views/clinic_information/ClinicInformation.test.js
  src/app/views/clinic_information/ClinicInformationPage.jsx
  src/app/views/clinic_information/ErrorBannerDetail.jsx
  src/app/views/clinic_information/ErrorBannerDetail.test.js
  src/app/views/clinic_information/LsoaTable.jsx
  src/app/views/clinic_information/LsoaTable.test.js
  src/app/views/clinic_information/RecentInvitationHistory.jsx
  src/app/views/clinic_information/WeeklyCapacityTable.jsx
  src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitaionCriteria.test.js
  src/app/views/clinic_information/clinic_invitation_criteria/ClinicInvitationCriteria.jsx
  src/app/views/clinic_summary/ClinicSummaryPage.jsx
  src/app/views/clinic_summary/ClinicSummaryTable.jsx
Labels: frontend

#64 Invitations Screens - Generate Invitation Confirmation
  src/app/components/Pagination.js
  src/app/helper/helperMethods.js
  src/app/styles/css/sass.css
  src/app/views/clinic_information/ClinicInformation.js
  src/app/views/clinic_information/WeeklyCapacityTable.jsx
  src/app/views/invitation_planning/helper.js
  src/app/views/invitation_summary/ConfirmationBanner.jsx
  src/app/views/invitation_summary/InvitationSummary.js
  src/app/views/invitation_summary/SummaryListFirst.jsx
  src/app/views/invitation_summary/SummaryListSecond.jsx
Labels: enhancement
