Repository NHSDigital/Galleri-Frontend, pull requests merged in 2024-01, with the labels that each got.

#93 Gal 777/accessibility invitation variables
  src/app/components/Header.jsx
  src/app/page.jsx
  src/app/styles/css/sass.css
  src/app/views/invitation_planning/ErrorInvitations.jsx
  src/app/views/invitation_planning/Errorinvitations.test.js
  src/app/views/invitation_planning/InvitationPlanning.js
  src/app/views/invitation_planning/InvitationPlanningPage.jsx
  src/app/views/invitation_planning/InvitationPlanningPage.test.js
  src/app/views/invitation_planning/NationalForecastUptakeTable.jsx
  src/app/views/invitation_planning/NationalForecastUptakeTable.test.js
  src/app/views/invitation_planning/QuintileTargetTable.jsx
  src/app/views/invitation_planning/QuintileTargetTable.test.js
Labels: frontend, accessibility

#94 Gal 775 & 776 /accessibility invitation summary
  jest.config.js
  package.json
  scripts/reports/perform-static-analysis.sh
  src/app/components/Header.jsx
  src/app/page.jsx
  src/app/styles/css/sass.css
  src/app/views/clinic_information/ClinicInformation.js
  src/app/views/invitation_summary/Actions.jsx
  src/app/views/invitation_summary/CheckDetailsBanner.jsx
  src/app/views/invitation_summary/CheckDetailsBanner.test.js
  src/app/views/invitation_summary/ClinicInfo.jsx
  src/app/views/invitation_summary/ClinicInfo.test.js
  src/app/views/invitation_summary/ConfirmationBanner.jsx
  src/app/views/invitation_summary/ConfirmationBanner.test.js
  src/app/views/invitation_summary/InvitationSummary.js
  src/app/views/invitation_summary/InvitationSummaryPage.jsx
  src/app/views/invitation_summary/InvitationSummaryPage.test.js
  src/app/views/invitation_summary/SummaryListFirst.jsx
  src/app/views/invitation_summary/SummaryListFirst.test.js
  src/app/views/invitation_summary/SummaryListSecond.jsx
  src/app/views/invitation_summary/SummaryListSecond.test.js
  src/app/views/start_page/Start.js
Labels: frontend, accessibility

#95 Feature/gal 334/create episode record
  src/app/context/AppStateContext.js
  src/app/views/clinic_information/ClinicInformation.js
  src/app/views/invitation_summary/InvitationSummary.js
Labels: enhancement

#99 Gal 381/privacy page
  src/app/page.jsx
  src/app/views/privacy_confirmation/PrivacyConfirmation.js
  src/app/views/privacy_confirmation/PrivacyConfirmation.test.js
  src/app/views/privacy_confirmation/PrivacyConfirmationPage.jsx
  src/app/views/referrals_summary/ReferralsSummary.js
Labels: frontend

#105 forecastUptake value should not exceed 100
  src/app/views/clinic_information/LsoaTable.jsx
  src/app/views/clinic_information/LsoaTable.test.js
Labels: bug

#73 Gal 703/setup use of nextauth library
  .env
  jsconfig.json
  package-lock.json
  package.json
  src/app/api/auth/[...nextauth]/route.ts
  src/app/components/Header.jsx
  src/app/components/NavMenu.jsx
  src/app/context/AppStateContext.js
  src/app/context/AuthProvider.tsx
  src/app/context/AutoSignOutProvider.jsx
  src/app/layout.jsx
  src/app/page.jsx
  src/app/signin/page.jsx
  src/app/styles/css/sass.css
  src/app/views/clinic_information/ClinicInformation.js
  src/app/views/clinic_summary/ClinicSummary.js
  src/app/views/clinic_summary/ClinicSummaryPage.jsx
  src/app/views/invitation_planning/InvitationPlanning.js
  src/app/views/invitation_summary/InvitationSummary.js
  src/app/views/privacy_confirmation/PrivacyConfirmation.js
  src/app/views/start_page/Start.js
  src/app/views/start_page/StartPage.jsx
  tsconfig.json
Labels: enhancement, frontend, dependencies
